### ISSUE TITLE
Update `Makefile`

### ISSUE THREAD

**Issue by ezio-melotti** [python/devguide#854]
- [x] `make clean` should also remove the `venv` (see #856)
- [x] `make clean-venv` should be added to only remove the `venv` (see #856)
- [x] `make check` should check for the default role (see #866)
- [x] `make htmlview` should be added (see #826)
- [x] `make venv` shouldn't print when called by other targets (see #867)

**Comment by ezio-melotti** [comment]
This is all done -- closing.
